
# About the Authors {-}

These credits are based on our [course contributors table guidelines](https://www.ottrproject.org/more_features.html#giving-credits-to-contributors).

&nbsp;
&nbsp;

|Credits|Names|
|-------|-----|
|**Pedagogy**||
|Lead Content Instructor|[Elizabeth Humphries] (Writing Code, Understanding Unfamiliar Code)|
|Content Authors| [Candace Savonen] (Annotating Your Code), [Carrie Wright] (Ethics of Using AI), [Ava Hoffman] (Refactoring Code)|
|Content Editor Reviewer | Howard Baek |
|**Technical**||
|Template Publishing Engineers|[Candace Savonen], [Carrie Wright], [Ava Hoffman]|
|Publishing Maintenance Engineer|[Candace Savonen]|
|Technical Publishing Stylists|[Carrie Wright], [Ava Hoffman], [Candace Savonen]|
|Package Developers ([ottrpal]) | [Candace Savonen], [John Muschelli], [Carrie Wright]|
|**Art and Design**||
|Figure Artists| [Candace Savonen], [Carrie Wright], [Ava Hoffman], [Elizabeth Humphries]|
|**Funding**||
|Funders| CS, CW, and HB were supported by the [National Cancer Institute (NCI)](https://www.cancer.gov/) under Grant [UE5CA254170](https://grantome.com/grant/NIH/UE5-CA254170-01). AMH and EMH were supported by the AnVIL Project through cooperative agreement awards from the National Human Genome Research Institute with cofunding from OD/ODSS to the Broad Institute (U24HG010262) and Johns Hopkins University (U24HG010263). |
|Funding Staff| [Sandra Ormbrek], [Shasta Nicholson] |

&nbsp;

Tools Used:

```{r, echo = FALSE}
devtools::session_info()
```

<!-- Author information -->

[FirstName LastName]: link to personal website
[John Muschelli]: https://johnmuschelli.com/
[Candace Savonen]: https://www.cansavvy.com/
[Carrie Wright]: https://carriewright11.github.io/
[Ava Hoffman]: https://www.avahoffman.com/
[Elizabeth Humphries]: https://www.linkedin.com/in/elizabeth-humphries-61202a103/
[Sandra Ormbrek]: https://hutchdatascience.org/ourteam/
[Shasta Nicholson]: https://www.linkedin.com/in/shastanicholson/


<!-- Links -->

[ottrpal]: https://github.com/jhudsl/ottrpal

<!-- Fill out this table using these instructions: https://github.com/jhudsl/OTTR_Template/wiki/How-to-give-credits

For JHU courses, You will need to add Ira as a credit:

|Content Publisher|[Ira Gooding]|
...
[Ira Gooding]: https://publichealth.jhu.edu/faculty/4130/ira-gooding
-->
